INFO - 开始运行脚本: MyConfig.py
INFO - 开始运行脚本: TestName.py
INFO - 开始运行脚本: entity\full.py
INFO - 脚本 entity\full.py 输出:
[INFO]  [Bee]======== Bee Version is: 1.6.0
INFO - 开始运行脚本: entity\naming.py
INFO - 开始运行脚本: entity\Orders.py
INFO - 开始运行脚本: entity\Orders01.py
INFO - 开始运行脚本: entity\Orders02.py
INFO - 开始运行脚本: entity\Orders2.py
INFO - 开始运行脚本: entity\Orders3.py
INFO - 开始运行脚本: entity\Orders4.py
INFO - 开始运行脚本: entity\Orders42.py
INFO - 开始运行脚本: entity\Orders5.py
INFO - 开始运行脚本: entity\Orders6.py
INFO - 脚本 entity\Orders6.py 输出:
{'id': 100001, 'name': 'Bee(ORM Framework)', 'price': 29.99, 'quantity': 5, 'customer_id': 123, 'order_date': '2023-10-01', 'status': 'Shipped', 'shipping_address': '123 Main St', 'payment_method': 'Credit Card', 'note': 'Leave at the front door'}
INFO - 开始运行脚本: entity\Orders7.py
INFO - 脚本 entity\Orders7.py 输出:
{'arg0': 100001, 'arg1': 'Bee(ORM Framework)', 'arg2': 29.99, 'arg3': 5, 'customer_id': 123, 'order_date': '2023-10-01', 'status': 'Shipped', 'shipping_address': '123 Main St', 'payment_method': 'Credit Card', 'note': 'Leave at the front door'}
INFO - 开始运行脚本: entity\Orders8.py
INFO - 开始运行脚本: entity\Orders_2025.py
INFO - 开始运行脚本: entity\Orders_202501.py
INFO - 开始运行脚本: entity\Student.py
INFO - 开始运行脚本: entity\Student2.py
INFO - 开始运行脚本: entity\Student3.py
INFO - 开始运行脚本: entity\Test.py
INFO - 开始运行脚本: exam\BatchInsertTest.py
ERROR - 脚本 exam\BatchInsertTest.py 运行失败: Command '['python', 'exam\\BatchInsertTest.py']' returned non-zero exit status 1.
INFO - 开始运行脚本: exam\BatchInsertTest2.py
ERROR - 脚本 exam\BatchInsertTest2.py 运行失败: Command '['python', 'exam\\BatchInsertTest2.py']' returned non-zero exit status 1.
INFO - 开始运行脚本: exam\BatchInsertTest3.py
ERROR - 脚本 exam\BatchInsertTest3.py 运行失败: Command '['python', 'exam\\BatchInsertTest3.py']' returned non-zero exit status 1.
INFO - 开始运行脚本: exam\BatchInsertTest4.py
ERROR - 脚本 exam\BatchInsertTest4.py 运行失败: Command '['python', 'exam\\BatchInsertTest4.py']' returned non-zero exit status 1.
INFO - 开始运行脚本: exam\ExceptionTest.py
INFO - 脚本 exam\ExceptionTest.py 输出:
[INFO]  [Bee]======== Bee Version is: 1.6.0
start...
define exception :  None
define exception :  --ConfigBeeException-- (error code: 500)
INFO - 开始运行脚本: exam\hello.py
ERROR - 脚本 exam\hello.py 运行失败: Command '['python', 'exam\\hello.py']' returned non-zero exit status 1.
INFO - 开始运行脚本: exam\SuidTest1.py
ERROR - 脚本 exam\SuidTest1.py 运行失败: Command '['python', 'exam\\SuidTest1.py']' returned non-zero exit status 1.
INFO - 开始运行脚本: exam\SuidTest10.py
ERROR - 脚本 exam\SuidTest10.py 运行失败: Command '['python', 'exam\\SuidTest10.py']' returned non-zero exit status 1.
INFO - 开始运行脚本: exam\SuidTest11Page.py
ERROR - 脚本 exam\SuidTest11Page.py 运行失败: Command '['python', 'exam\\SuidTest11Page.py']' returned non-zero exit status 1.
INFO - 开始运行脚本: exam\SuidTest12_insert.py
ERROR - 脚本 exam\SuidTest12_insert.py 运行失败: Command '['python', 'exam\\SuidTest12_insert.py']' returned non-zero exit status 1.
INFO - 开始运行脚本: exam\SuidTest13_insert.py
ERROR - 脚本 exam\SuidTest13_insert.py 运行失败: Command '['python', 'exam\\SuidTest13_insert.py']' returned non-zero exit status 1.
INFO - 开始运行脚本: exam\SuidTest32_update_delete.py
ERROR - 脚本 exam\SuidTest32_update_delete.py 运行失败: Command '['python', 'exam\\SuidTest32_update_delete.py']' returned non-zero exit status 1.
INFO - 开始运行脚本: exam\SuidTest4.py
ERROR - 脚本 exam\SuidTest4.py 运行失败: Command '['python', 'exam\\SuidTest4.py']' returned non-zero exit status 1.
INFO - 开始运行脚本: exam\SuidTest42.py
ERROR - 脚本 exam\SuidTest42.py 运行失败: Command '['python', 'exam\\SuidTest42.py']' returned non-zero exit status 1.
INFO - 开始运行脚本: exam\SuidTest6.py
ERROR - 脚本 exam\SuidTest6.py 运行失败: Command '['python', 'exam\\SuidTest6.py']' returned non-zero exit status 1.
INFO - 开始运行脚本: exam15\BatchInsertTest2.py
ERROR - 脚本 exam15\BatchInsertTest2.py 运行失败: Command '['python', 'exam15\\BatchInsertTest2.py']' returned non-zero exit status 1.
INFO - 开始运行脚本: exam15\ByIdTest.py
ERROR - 脚本 exam15\ByIdTest.py 运行失败: Command '['python', 'exam15\\ByIdTest.py']' returned non-zero exit status 1.
INFO - 开始运行脚本: exam15\DdlTest.py
ERROR - 脚本 exam15\DdlTest.py 运行失败: Command '['python', 'exam15\\DdlTest.py']' returned non-zero exit status 1.
INFO - 开始运行脚本: exam15\DdlTest2.py
ERROR - 脚本 exam15\DdlTest2.py 运行失败: Command '['python', 'exam15\\DdlTest2.py']' returned non-zero exit status 1.
INFO - 开始运行脚本: exam15\DdlTest3.py
ERROR - 脚本 exam15\DdlTest3.py 运行失败: Command '['python', 'exam15\\DdlTest3.py']' returned non-zero exit status 1.
INFO - 开始运行脚本: exam15\DdlTest4.py
ERROR - 脚本 exam15\DdlTest4.py 运行失败: Command '['python', 'exam15\\DdlTest4.py']' returned non-zero exit status 1.
INFO - 开始运行脚本: exam15\DdlTest5.py
ERROR - 脚本 exam15\DdlTest5.py 运行失败: Command '['python', 'exam15\\DdlTest5.py']' returned non-zero exit status 1.
INFO - 开始运行脚本: exam15\PreTest.py
ERROR - 脚本 exam15\PreTest.py 运行失败: Command '['python', 'exam15\\PreTest.py']' returned non-zero exit status 1.
INFO - 开始运行脚本: exam15\PreTest2.py
ERROR - 脚本 exam15\PreTest2.py 运行失败: Command '['python', 'exam15\\PreTest2.py']' returned non-zero exit status 1.
INFO - 开始运行脚本: exam15\PreTest3.py
ERROR - 脚本 exam15\PreTest3.py 运行失败: Command '['python', 'exam15\\PreTest3.py']' returned non-zero exit status 1.
INFO - 开始运行脚本: exam15\SelectFun.py
ERROR - 脚本 exam15\SelectFun.py 运行失败: Command '['python', 'exam15\\SelectFun.py']' returned non-zero exit status 1.
INFO - 开始运行脚本: exam15\SuidTest1.py
ERROR - 脚本 exam15\SuidTest1.py 运行失败: Command '['python', 'exam15\\SuidTest1.py']' returned non-zero exit status 1.
INFO - 开始运行脚本: exam16\bugTest.py
ERROR - 脚本 exam16\bugTest.py 运行失败: Command '['python', 'exam16\\bugTest.py']' returned non-zero exit status 1.
INFO - 开始运行脚本: exam16\cacheTest.py
ERROR - 脚本 exam16\cacheTest.py 运行失败: Command '['python', 'exam16\\cacheTest.py']' returned non-zero exit status 1.
INFO - 开始运行脚本: exam16\cacheTest2.py
ERROR - 脚本 exam16\cacheTest2.py 运行失败: Command '['python', 'exam16\\cacheTest2.py']' returned non-zero exit status 1.
INFO - 开始运行脚本: exam16\cacheTest3.py
ERROR - 脚本 exam16\cacheTest3.py 运行失败: Command '['python', 'exam16\\cacheTest3.py']' returned non-zero exit status 1.
INFO - 开始运行脚本: exam16\cacheTest4.py
ERROR - 脚本 exam16\cacheTest4.py 运行失败: Command '['python', 'exam16\\cacheTest4.py']' returned non-zero exit status 1.
INFO - 开始运行脚本: exam16\conditionTest.py
ERROR - 脚本 exam16\conditionTest.py 运行失败: Command '['python', 'exam16\\conditionTest.py']' returned non-zero exit status 1.
INFO - 开始运行脚本: exam16\conditionTest2.py
ERROR - 脚本 exam16\conditionTest2.py 运行失败: Command '['python', 'exam16\\conditionTest2.py']' returned non-zero exit status 1.
INFO - 开始运行脚本: exam16\conditionTest3_paging.py
ERROR - 脚本 exam16\conditionTest3_paging.py 运行失败: Command '['python', 'exam16\\conditionTest3_paging.py']' returned non-zero exit status 1.
INFO - 开始运行脚本: exam16\conditionTest4_delete.py
ERROR - 脚本 exam16\conditionTest4_delete.py 运行失败: Command '['python', 'exam16\\conditionTest4_delete.py']' returned non-zero exit status 1.
INFO - 开始运行脚本: exam16\conditionTest5_update.py
ERROR - 脚本 exam16\conditionTest5_update.py 运行失败: Command '['python', 'exam16\\conditionTest5_update.py']' returned non-zero exit status 1.
INFO - 开始运行脚本: exam16\conditionTest5_update1.py
ERROR - 脚本 exam16\conditionTest5_update1.py 运行失败: Command '['python', 'exam16\\conditionTest5_update1.py']' returned non-zero exit status 1.
INFO - 开始运行脚本: exam16\conditionTest5_update2.py
ERROR - 脚本 exam16\conditionTest5_update2.py 运行失败: Command '['python', 'exam16\\conditionTest5_update2.py']' returned non-zero exit status 1.
INFO - 开始运行脚本: exam16\conditionTest5_update3.py
ERROR - 脚本 exam16\conditionTest5_update3.py 运行失败: Command '['python', 'exam16\\conditionTest5_update3.py']' returned non-zero exit status 1.
INFO - 开始运行脚本: exam16\conditionTest5_update4.py
ERROR - 脚本 exam16\conditionTest5_update4.py 运行失败: Command '['python', 'exam16\\conditionTest5_update4.py']' returned non-zero exit status 1.
INFO - 开始运行脚本: exam16\conditionTest5_update4_3.py
ERROR - 脚本 exam16\conditionTest5_update4_3.py 运行失败: Command '['python', 'exam16\\conditionTest5_update4_3.py']' returned non-zero exit status 1.
INFO - 开始运行脚本: exam16\conditionTest5_update5.py
ERROR - 脚本 exam16\conditionTest5_update5.py 运行失败: Command '['python', 'exam16\\conditionTest5_update5.py']' returned non-zero exit status 1.
INFO - 开始运行脚本: exam16\conditionTest5_update6.py
ERROR - 脚本 exam16\conditionTest5_update6.py 运行失败: Command '['python', 'exam16\\conditionTest5_update6.py']' returned non-zero exit status 1.
INFO - 开始运行脚本: exam16\conditionTest5_update7.py
ERROR - 脚本 exam16\conditionTest5_update7.py 运行失败: Command '['python', 'exam16\\conditionTest5_update7.py']' returned non-zero exit status 1.
INFO - 开始运行脚本: exam16\conditionTest5_update8.py
ERROR - 脚本 exam16\conditionTest5_update8.py 运行失败: Command '['python', 'exam16\\conditionTest5_update8.py']' returned non-zero exit status 1.
INFO - 开始运行脚本: exam16\config_test.py
ERROR - 脚本 exam16\config_test.py 运行失败: Command '['python', 'exam16\\config_test.py']' returned non-zero exit status 1.
INFO - 开始运行脚本: exam16\Create.py
ERROR - 脚本 exam16\Create.py 运行失败: Command '['python', 'exam16\\Create.py']' returned non-zero exit status 1.
INFO - 开始运行脚本: exam16\full_type.py
ERROR - 脚本 exam16\full_type.py 运行失败: Command '['python', 'exam16\\full_type.py']' returned non-zero exit status 1.
INFO - 开始运行脚本: exam16\full_type2.py
ERROR - 脚本 exam16\full_type2.py 运行失败: Command '['python', 'exam16\\full_type2.py']' returned non-zero exit status 1.
INFO - 开始运行脚本: exam16\full_type3.py
ERROR - 脚本 exam16\full_type3.py 运行失败: Command '['python', 'exam16\\full_type3.py']' returned non-zero exit status 1.
INFO - 开始运行脚本: exam16\full_type4.py
ERROR - 脚本 exam16\full_type4.py 运行失败: Command '['python', 'exam16\\full_type4.py']' returned non-zero exit status 1.
INFO - 开始运行脚本: exam16\genBeanTest.py
ERROR - 脚本 exam16\genBeanTest.py 运行失败: Command '['python', 'exam16\\genBeanTest.py']' returned non-zero exit status 1.
INFO - 开始运行脚本: exam16\model_to_sql.py
INFO - 脚本 exam16\model_to_sql.py 输出:
CREATE TABLE user (
    ID INTEGER PRIMARY KEY,
    OrgID INTEGER,
    RoleID INTEGER,
    Name VARCHAR(64) UNIQUE,
    Password VARCHAR(16),
    Tel VARCHAR(16) UNIQUE,
    Remark TEXT
);
INFO - 开始运行脚本: exam16\model_to_sql6.py
INFO - 脚本 exam16\model_to_sql6.py 输出:
CREATE TABLE user (
    ID INTEGER PRIMARY KEY,
    OrgID INTEGER,
    RoleID INTEGER,
    Name VARCHAR(64) UNIQUE,
    Password VARCHAR(16),
    Tel VARCHAR(16) UNIQUE,
    Remark TEXT
);
CREATE TABLE organization (
    ID INTEGER PRIMARY KEY,
    TypeID INTEGER,
    Name VARCHAR(64) UNIQUE,
    Remark TEXT
);
INFO - 开始运行脚本: exam16\model_to_sql7.py
INFO - 脚本 exam16\model_to_sql7.py 输出:
CREATE TABLE user (
    ID INTEGER PRIMARY KEY,
    OrgID INTEGER,
    RoleID INTEGER,
    Name VARCHAR(64) UNIQUE,
    Password VARCHAR(16),
    Tel VARCHAR(16) UNIQUE,
    Remark TEXT
);
CREATE TABLE user (
    ID INTEGER PRIMARY KEY,
    OrgID INTEGER,
    RoleID INTEGER,
    Name VARCHAR(64) UNIQUE,
    Password VARCHAR(16),
    Tel VARCHAR(16) UNIQUE,
    Remark TEXT
);
INFO - 开始运行脚本: exam16\namingTest.py
ERROR - 脚本 exam16\namingTest.py 运行失败: Command '['python', 'exam16\\namingTest.py']' returned non-zero exit status 1.
INFO - 开始运行脚本: exam16\oracle_test.py
INFO - 开始运行脚本: exam16\orm.py
INFO - 开始运行脚本: exam16\select_someFields_paging.py
ERROR - 脚本 exam16\select_someFields_paging.py 运行失败: Command '['python', 'exam16\\select_someFields_paging.py']' returned non-zero exit status 1.
INFO - 开始运行脚本: exam16\SuidTest1.py
ERROR - 脚本 exam16\SuidTest1.py 运行失败: Command '['python', 'exam16\\SuidTest1.py']' returned non-zero exit status 1.
INFO - 开始运行脚本: exam16\SuidTest2.py
ERROR - 脚本 exam16\SuidTest2.py 运行失败: Command '['python', 'exam16\\SuidTest2.py']' returned non-zero exit status 1.
INFO - 开始运行脚本: exam16\Test.py
INFO - 脚本 exam16\Test.py 输出:
[INFO]  [Bee]======== Bee Version is: 1.6.0
user_name,class_name
INFO - 开始运行脚本: other\custom_config.py
INFO - 脚本 other\custom_config.py 输出:
[INFO]  [Bee]======== Bee Version is: 1.6.0
start
[DEBUG]  [Bee]======== HoneyConfig instance...
[INFO]  [Bee]======== Loading config file: resources\bee.properties
[INFO]  [Bee]======== Reset db_config_data
[INFO]  [Bee] sql>>> select SQL: select id, name, remark from orders where name = ?
[INFO]  [Bee] sql>>> params: ['bee']
[INFO]  [Bee]======== Database driver use sqlite3 for SQLite
[INFO]  [Bee]========  | <--  select rows: 0
[]
finished
INFO - 开始运行脚本: other\no_suid_Test.py
INFO - 脚本 other\no_suid_Test.py 输出:
[INFO]  [Bee]======== Bee Version is: 1.6.0
user_name,class_name
aaaBb
aaaBb
userName
testName
Testname
user_name
user_name
TestName
INFO - 开始运行脚本: other\SuidTest1.py
INFO - 脚本 other\SuidTest1.py 输出:
[INFO]  [Bee]======== Bee Version is: 1.6.0
start
[DEBUG]  [Bee]======== HoneyConfig instance...
[INFO]  [Bee]======== Loading config file: E:\JavaWeb\eclipse-workspace202312\PyTest\resources\bee.properties
[INFO]  [Bee]======== adjust the SQLite db file path to: E:\JavaWeb\eclipse-workspace202312\PyTest\resources\bee.db
[INFO]  [Bee]======== Database driver use sqlite3 for SQLite
[{'id': 1, 'name': 'bee', 'remark': 'remark test'}, {'id': 2, 'name': 'bee1', 'remark': 'remark test1'}]
finished
INFO - 开始运行脚本: test\c4.py
INFO - 脚本 test\c4.py 输出:
start
-----------__new__---------
HoneyConfig instance...
None
INFO - 开始运行脚本: test\ccc.py
INFO - 脚本 test\ccc.py 输出:
start
None
INFO - 开始运行脚本: test\if_test.py
INFO - 脚本 test\if_test.py 输出:
begain.....
 start is 0, ---- not start---
INFO - 开始运行脚本: test\pc.py
INFO - 脚本 test\pc.py 输出:
Recorded child classes: []
INFO - 开始运行脚本: test\pc2.py
INFO - 脚本 test\pc2.py 输出:
00000
2222
Recorded child classes: ['Child1', 'Child2']
INFO - 开始运行脚本: test\pc3.py
INFO - 脚本 test\pc3.py 输出:
Recorded child classes: ['Child1', 'Child2']
INFO - 开始运行脚本: test\pc4.py
INFO - 脚本 test\pc4.py 输出:
Recorded child classes: ['Child1', 'Child2']
INFO - 开始运行脚本: test\pc5.py
INFO - 脚本 test\pc5.py 输出:
00000
00000
Recorded child classes: ['Child1', 'Child2']
INFO - 开始运行脚本: test\pc6.py
INFO - 脚本 test\pc6.py 输出:
00000 a
2222 b
Recorded child classes: ['Child1', 'Child2']
[<class '__main__.Child1'>, <class '__main__.Child2'>]
INFO - 开始运行脚本: test\pc7.py
INFO - 脚本 test\pc7.py 输出:
00000 a
2222 b
Recorded child classes: ['Child1', 'Child2']
INFO - 开始运行脚本: test\table2entity.py
INFO - 脚本 test\table2entity.py 输出:
from datetime import datetime, date, time
from typing import Annotated, Dict, List, Set, Tuple, Optional

class testName:
    """实体类对应数据库表 test_name"""
    id: int = 
    myName: Annotated[str, "length=255"] = None
    name2: Annotated[str, "length=100"] = None
    myPrice: float = None
    createdAt: datetime
    updatedTime: time
    flag: bool = None
    set0: str = None
    map: str = None
    list0: str = None
    list1: str = None
    remark: Annotated[str, "length=255"] = None
    tuple0: str = None
    descstr: Annotated[str, "length=255"] = None
    modifyDate: datetime
    updatedAt2: datetime
    set1: str = None
    map1: str = None
    tuple1: str = None
    setTwo: str = None
    mapTwo: str = None
    tupleTwo: str = None
    listTwo: str = None
    ttt: Any = None

    def __repr__(self):
        return str(self.__dict__)
INFO - 开始运行脚本: test\table2entity2.py
INFO - 脚本 test\table2entity2.py 输出:
from datetime import datetime, date, time
from typing import Annotated, Dict, List, Set, Tuple, Optional

class testName:
    """实体类对应数据库表 test_name"""
    id: int = 
    myName: Annotated[str, "length=255"] = None
    name2: Annotated[str, "length=100"] = None
    myPrice: float = None
    createdAt: datetime
    updatedTime: time
    flag: bool = None
    set0: str = None
    map: str = None
    list0: str = None
    list1: str = None
    remark: Annotated[str, "length=255"] = None
    tuple0: str = None
    descstr: Annotated[str, "length=255"] = None
    modifyDate: datetime
    updatedAt2: datetime
    set1: str = None
    map1: str = None
    tuple1: str = None
    setTwo: str = None
    mapTwo: str = None
    tupleTwo: str = None
    listTwo: str = None
    ttt: Any = None

    def __repr__(self):
        return str(self.__dict__)
INFO - 开始运行脚本: test\tableFromMysql2entity.py
INFO - 开始运行脚本: test\Type.py
INFO - 脚本 test\Type.py 输出:
[INFO]  [Bee]======== Bee Version is: 1.6.0
{'__module__': 'entity.full', '__annotations__': {'id': <class 'int'>, 'name': <class 'str'>, 'name2': typing.Annotated[str, 'length = 100'], 'name3': typing.Annotated[str, 'len = 100'], 'name4': <bee.typing.String object at 0x00000211A05791C0>, 'name5': <class 'bee.typing.String'>, 'price': <class 'float'>, 'created_at': <class 'datetime.datetime'>, 'updated_time': <class 'datetime.time'>, 'flag': <class 'bool'>, 'set0': <class 'set'>, 'map': <class 'dict'>, 'list0': <class 'list'>, 'list1': typing.List, 'tuple0': <class 'tuple'>, 'descstr': <class 'str'>, 'modify_date': <class 'datetime.date'>, 'updated_at2': <class 'datetime.date'>, 'set1': typing.Set, 'map1': typing.Dict, 'tuple1': typing.Tuple, 'ttt': <class 'bytes'>}, 'id': None, 'name': None, 'price': None, 'flag': None, 'set0': None, 'map': None, 'list0': None, 'list1': None, 'remark': None, 'tuple0': None, 'descstr': None, 'set1': None, 'map1': None, 'tuple1': None, 'ttt': None, '__repr__': <function Entity.__repr__ at 0x00000211A0567D80>, '__dict__': <attribute '__dict__' of 'Entity' objects>, '__weakref__': <attribute '__weakref__' of 'Entity' objects>, '__doc__': None}
{'__module__': 'entity.full', '__annotations__': {'id': <class 'int'>, 'name': <class 'str'>, 'name2': typing.Annotated[str, 'length = 100'], 'name3': typing.Annotated[str, 'len = 100'], 'name4': <bee.typing.String object at 0x00000211A05791C0>, 'name5': <class 'bee.typing.String'>, 'price': <class 'float'>, 'created_at': <class 'datetime.datetime'>, 'updated_time': <class 'datetime.time'>, 'flag': <class 'bool'>, 'set0': <class 'set'>, 'map': <class 'dict'>, 'list0': <class 'list'>, 'list1': typing.List, 'tuple0': <class 'tuple'>, 'descstr': <class 'str'>, 'modify_date': <class 'datetime.date'>, 'updated_at2': <class 'datetime.date'>, 'set1': typing.Set, 'map1': typing.Dict, 'tuple1': typing.Tuple, 'ttt': <class 'bytes'>}, 'id': None, 'name': None, 'price': None, 'flag': None, 'set0': None, 'map': None, 'list0': None, 'list1': None, 'remark': None, 'tuple0': None, 'descstr': None, 'set1': None, 'map1': None, 'tuple1': None, 'ttt': None, '__repr__': <function Entity.__repr__ at 0x00000211A0567D80>, '__dict__': <attribute '__dict__' of 'Entity' objects>, '__weakref__': <attribute '__weakref__' of 'Entity' objects>, '__doc__': None}
dict_keys(['id', 'name', 'name2', 'name3', 'name4', 'name5', 'price', 'created_at', 'updated_time', 'flag', 'set0', 'map', 'list0', 'list1', 'remark', 'tuple0', 'descstr', 'modify_date', 'updated_at2', 'set1', 'map1', 'tuple1', 'ttt'])
INFO - 所有脚本运行完成
